In [2]:
import pandas as pd
df = pd.read_csv("telco_churn_data.csv")

In [3]:
df

,Customer ID,Referred a Friend,Number of Referrals,Tenure in Months,Offer,Phone Service,Avg Monthly Long Distance Charges,Multiple Lines,Internet Service,Internet Type,...,Latitude,Longitude,Population,Churn Value,CLTV,Churn Category,Churn Reason,Total Customer Svc Requests,Product/Service Issues Reported,Customer Satisfaction
0,8779-QRDMV,No,0,1,None,No,0.00,No,Yes,Fiber Optic,...,34.023810,-118.156582,68701,1,5433,Competitor,Competitor offered more data,5,0,NaN
1,7495-OOKFY,Yes,1,8,Offer E,Yes,48.85,Yes,Yes,Cable,...,34.044271,-118.185237,55668,1,5302,Competitor,Competitor made better offer,5,0,NaN
2,1658-BYGOY,No,0,18,Offer D,Yes,11.33,Yes,Yes,Fiber Optic,...,34.108833,-118.229715,47534,1,3179,Competitor,Competitor made better offer,1,0,NaN
3,4598-XLKNJ,Yes,1,25,Offer C,Yes,19.76,No,Yes,Fiber Optic,...,33.936291,-118.332639,27778,1,5337,Dissatisfaction,Limited range of services,1,1,2.0
4,4846-WHAFZ,Yes,1,37,Offer C,Yes,6.33,Yes,Yes,Cable,...,33.972119,-118.020188,26265,1,2793,Price,Extra data charges,1,0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,No,0,72,None,Yes,22.77,No,No,None,...,34.341737,-116.539416,2182,0,5306,NaN,NaN,0,0,NaN
7039,6840-RESVB,Yes,1,24,Offer C,Yes,36.05,Yes,Yes,DSL,...,34.667815,-117.536183,18980,0,2140,NaN,NaN,2,0,NaN
7040,2234-XADUH,Yes,4,72,None,Yes,29.66,Yes,Yes,Cable,...,34.559882,-115.637164,42,0,5560,NaN,NaN,2,0,4.0
7041,4801-JZAZL,Yes,1,11,None,No,0.00,No,Yes,DSL,...,34.167800,-116.864330,301,0,2793,NaN,NaN,0,0,NaN
7042,3186-AJIEK,No,0,66,None,Yes,30.96,No,Yes,Fiber Optic,...,34.424926,-117.184503,28819,0,5097,NaN,NaN,1,2,NaN

In [4]:
df.dtypes

Customer ID                           object
Referred a Friend                     object
Number of Referrals                    int64
Tenure in Months                       int64
Offer                                 object
Phone Service                         object
Avg Monthly Long Distance Charges    float64
Multiple Lines                        object
Internet Service                      object
Internet Type                         object
Avg Monthly GB Download                int64
Online Security                       object
Online Backup                         object
Device Protection Plan                object
Premium Tech Support                  object
Streaming TV                          object
Streaming Movies                      object
Streaming Music                       object
Unlimited Data                        object
Contract                              object
Paperless Billing                     object
Payment Method                        object
Monthly Charge                       float64
Total Regular Charges                float64
Total Refunds                        float64
Total Extra Data Charges             float64
Total Long Distance Charges          float64
Gender                                object
Age                                    int64
Under 30                              object
Senior Citizen                        object
Married                               object
Dependents                            object
Number of Dependents                   int64
City                                  object
Zip Code                               int64
Latitude                             float64
Longitude                            float64
Population                             int64
Churn Value                            int64
CLTV                                   int64
Churn Category                        object
Churn Reason                          object
Total Customer Svc Requests            int64
Product/Service Issues Reported        int64
Customer Satisfaction                float64
dtype: object

In [5]:
df.drop("Customer ID",axis = "columns",inplace = True)

In [6]:
df.dtypes

Referred a Friend                     object
Number of Referrals                    int64
Tenure in Months                       int64
Offer                                 object
Phone Service                         object
Avg Monthly Long Distance Charges    float64
Multiple Lines                        object
Internet Service                      object
Internet Type                         object
Avg Monthly GB Download                int64
Online Security                       object
Online Backup                         object
Device Protection Plan                object
Premium Tech Support                  object
Streaming TV                          object
Streaming Movies                      object
Streaming Music                       object
Unlimited Data                        object
Contract                              object
Paperless Billing                     object
Payment Method                        object
Monthly Charge                       float64
Total Regular Charges                float64
Total Refunds                        float64
Total Extra Data Charges             float64
Total Long Distance Charges          float64
Gender                                object
Age                                    int64
Under 30                              object
Senior Citizen                        object
Married                               object
Dependents                            object
Number of Dependents                   int64
City                                  object
Zip Code                               int64
Latitude                             float64
Longitude                            float64
Population                             int64
Churn Value                            int64
CLTV                                   int64
Churn Category                        object
Churn Reason                          object
Total Customer Svc Requests            int64
Product/Service Issues Reported        int64
Customer Satisfaction                float64
dtype: object

In [7]:
for col in df:
    if(df[col].dtypes == 'object'):
        print(f'{col}: {df[col].unique()}')

Referred a Friend: ['No' 'Yes']
Offer: ['None' 'Offer E' 'Offer D' 'Offer C' 'Offer B' 'Offer A']
Phone Service: ['No' 'Yes']
Multiple Lines: ['No' 'Yes']
Internet Service: ['Yes' 'No']
Internet Type: ['Fiber Optic' 'Cable' 'DSL' 'None']
Online Security: ['No' 'Yes']
Online Backup: ['No' 'Yes']
Device Protection Plan: ['Yes' 'No']
Premium Tech Support: ['No' 'Yes']
Streaming TV: ['No' 'Yes']
Streaming Movies: ['Yes' 'No']
Streaming Music: ['No' 'Yes']
Unlimited Data: ['No' 'Yes']
Contract: ['Month-to-Month' 'One Year' 'Two Year']
Paperless Billing: ['Yes' 'No']
Payment Method: ['Bank Withdrawal' 'Credit Card' 'Mailed Check']
Gender: ['Male' 'Female']
Under 30: ['No' 'Yes']
Senior Citizen: ['Yes' 'No']
Married: ['No' 'Yes']
Dependents: ['No' 'Yes']
City: ['Los Angeles' 'Inglewood' 'Whittier' ... 'Topaz' 'Jacumba' 'Holtville']
Churn Category: ['Competitor' 'Dissatisfaction' 'Price' 'Other' 'Attitude' nan]
Churn Reason: ['Competitor offered more data' 'Competitor made better offer'
 'Limited range of services' 'Extra data charges'
 'Competitor had better devices' "Don't know" 'Service dissatisfaction'
 'Lack of affordable download/upload speed' 'Product dissatisfaction'
 'Long distance charges' 'Poor expertise of online support'
 'Attitude of support person' 'Network reliability'
 'Competitor offered higher download speeds' 'Moved' 'Price too high'
 'Attitude of service provider' 'Poor expertise of phone support'
 'Deceased' nan 'Lack of self-service on Website']

In [8]:
yes_no = ['Referred a Friend','Phone Service','Multiple Lines','Internet Service','Online Security','Online Backup','Device Protection Plan','Premium Tech Support','Streaming TV','Streaming Movies','Streaming Music','Unlimited Data','Paperless Billing','Under 30','Senior Citizen','Married','Dependents',]

for i in yes_no:
    df[i].replace({'Yes':1,'No':0},inplace = True)

In [10]:
for col in df:
    print(f'{col}: {df[col].unique()}')

Referred a Friend: [0 1]
Number of Referrals: [ 0  1  6  2  4  3  7  5  8  9 10 11]
Tenure in Months: [ 1  8 18 25 37 27 58 15  7 11  3 13 16 24  4 32 54  2 21 55  5 20 65 49
 43 56 52 33 30 46  9 10 35 44 62 14 12 17 39 68 34 22 19 23 42 41 57 38
 29 66 69 40 31 59 36 45 53 70 47 50 51 72 26  6 28 48 61 71 60 64 67 63]
Offer: ['None' 'Offer E' 'Offer D' 'Offer C' 'Offer B' 'Offer A']
Phone Service: [0 1]
Avg Monthly Long Distance Charges: [ 0.   48.85 11.33 ... 44.99 44.98  8.62]
Multiple Lines: [0 1]
Internet Service: [1 0]
Internet Type: ['Fiber Optic' 'Cable' 'DSL' 'None']
Avg Monthly GB Download: [ 9 19 57 13 15 20 33 26 21 32 31 12 10  8 16  2 11  6 14  0 30 29 24 28
 23 22  7 18 25  4  3  5 27 58 17 53 75 56 52 76 64 45 63 62 78 80 84 65
 90 46 43 94 51 48 73 69 71 42 41 59 47 82 85]
Online Security: [0 1]
Online Backup: [0 1]
Device Protection Plan: [1 0]
Premium Tech Support: [0 1]
Streaming TV: [0 1]
Streaming Movies: [1 0]
Streaming Music: [0 1]
Unlimited Data: [0 1]
Contract: ['Month-to-Month' 'One Year' 'Two Year']
Paperless Billing: [1 0]
Payment Method: ['Bank Withdrawal' 'Credit Card' 'Mailed Check']
Monthly Charge: [41.236 83.876 99.268 ... 72.    65.45  78.7  ]
Total Regular Charges: [  39.65  633.3  1752.55 ... 7362.9   346.45 6844.5 ]
Total Refunds: [ 0.   45.61 13.43 40.95 11.05 29.84 49.57 12.07 40.64 10.2  17.88 37.55
 48.09 32.46 20.23 12.59 43.31  8.13 46.64 23.33 47.2  33.25 33.73 49.06
 25.79 15.24 26.99 44.58 20.16  8.88 12.48  6.79 39.29 44.31  5.49 25.67
  9.49 29.17 19.25 45.69 29.88 39.93 26.98 11.83 16.58 17.16 18.85 37.64
 41.2  12.19 45.81 49.53 21.52 29.   29.99 21.08 36.4  21.17  6.26 17.91
 34.67 28.93 41.23 47.73 40.46 15.41 38.98 16.73 27.15 45.82 39.18 31.05
 20.45  6.65 47.04 15.2   1.69 43.66 24.36 27.89  6.11  7.43 25.07 48.66
 36.52 38.09 24.98 21.71 36.78 30.75 25.55 17.19 33.1  32.71  4.76 44.81
  3.33 19.16 31.58  1.09 18.64 44.17 17.76 33.07  8.74  4.48 36.6  33.43
 45.44 18.55 33.21 48.25 21.72 21.69 14.22 45.37 27.6  10.17 36.44 13.03
 23.89 11.   34.29 48.26 35.82 15.73  9.36 19.67 39.27 41.85 40.   12.81
  4.73 27.38 14.24 13.01 11.45 28.35  7.39 35.05 41.18 30.46 48.61 26.02
 38.48 14.23 40.15 48.95 24.44  9.68 23.72 20.29 48.54  4.96 18.21  1.27
 22.96 28.49 19.5   8.35 35.7  17.01 34.69  4.93 35.34 18.39 27.3  44.16
 34.09 36.61 18.72 44.63 23.97 38.42  1.48  2.93 10.76 20.28 42.18 40.79
 41.21  2.29 24.08 36.29 30.26  4.6  41.67 15.62 46.78 14.49 25.84 16.97
 23.67 46.56 27.09 10.23 15.57 26.55  3.2  21.6  17.14  5.73 32.09  1.83
 47.19 14.21 38.15  8.3  31.39 12.55 11.48 43.38 49.37  9.34 38.61 37.06
 43.25 23.28 45.07 44.9  23.61 19.89 38.84  1.01 14.67 37.37 21.32 36.04
 49.51 47.91 11.72 29.76  1.99 40.62 18.84  9.22 33.8   9.73 46.07 47.87
 39.99 14.76  2.24 42.89 16.12 38.37 47.36 33.76 12.8  23.01 12.16 45.75
 28.42 37.03 38.46 46.66 35.61 18.89  1.66 17.6  21.35 29.32 23.92 29.5
 16.86 42.64  1.31 10.57 34.44 13.07 22.34 43.95 37.44 25.57 14.93 46.75
 28.7   2.28 47.02 16.85 29.11 32.55  5.44 27.79 43.68 41.74  2.18  3.26
 26.87 10.47 37.45 34.16 17.5  11.37 46.81 15.02 19.63 45.47 39.92 22.55
  3.34 17.05 38.33 47.79 24.92 40.54  5.55 30.22  5.47 44.   28.98 49.38
 37.68 18.17 36.38 26.83 29.21 18.88 33.67 17.3  17.03  3.55 25.62 18.62
  9.39  5.9   5.01 42.57 42.43  4.7  21.53 21.58 35.28 28.83 38.57 29.41
 10.65 42.29 16.38 36.66 39.45 29.64 26.32 11.85 16.26 20.17 32.59 16.36
 22.53  6.72 36.22 38.34 28.08 17.96 33.29 24.9  15.38  5.15  6.41 41.66
 46.06 33.13 12.66 48.79  3.59 44.86 34.83 49.79 44.53 47.45 13.37  2.81
 44.13 23.13  2.76 46.99 23.16 44.42 48.59 11.8  17.17 15.76  2.97 15.31
 45.54 14.15 32.53 22.97 21.25 36.02 39.68 23.39 20.87 26.7   3.85  3.51
 35.23  9.48 36.13 44.51  4.08 34.45 16.96 16.91 43.12 49.76 23.5  29.95
  9.99 33.24 28.63 10.7  36.92 27.01 42.34 34.47  9.79 26.37  8.96 21.9
  4.25 16.56 10.28 46.67 14.78 49.23 35.01  9.35 37.04 49.24 32.65 39.15
 18.78 14.57 49.22 16.27  5.83 35.44 29.29 47.59 46.39 24.07  8.5  23.47
 29.59 28.09  6.49 34.59 47.55 37.01 43.76 25.98 12.26 37.49 19.13  1.65
 31.9  21.81 15.17 14.3  22.72  8.53 46.26 15.43 25.49 17.33 45.6  25.24
  2.62 36.07 29.93 23.79 22.4  16.89  7.3  16.99 41.33 30.45 30.14 24.99
 30.53 32.24  4.68  4.18  2.21 19.32 25.92 45.46 25.42 43.96 38.65 49.02
 19.12 20.19 26.84 40.41 19.31 48.23 45.38 27.24]
Total Extra Data Charges: [   0.    120.    327.   ...  229.29   17.84 4344.  ]
Total Long Distance Charges: [   0.    390.8   203.94 ...  865.2  2135.52 2043.36]
Gender: ['Male' 'Female']
Age: [78 74 71 80 72 76 66 70 77 65 67 68 69 79 75 73 37 19 31 23 38 21 29 61
 27 20 56 51 48 32 34 41 30 26 62 64 45 53 63 42 24 54 39 43 50 22 40 47
 60 52 55 59 49 58 25 28 33 44 57 46 36 35]
Under 30: [0 1]
Senior Citizen: [1 0]
Married: [0 1]
Dependents: [0 1]
Number of Dependents: [0 1 3 2 5 4 6 7 8 9]
City: ['Los Angeles' 'Inglewood' 'Whittier' ... 'Topaz' 'Jacumba' 'Holtville']
Zip Code: [90022 90063 90065 ... 91934 92105 92250]
Latitude: [34.02381  34.044271 34.108833 ... 32.649787 32.741859 32.811001]
Longitude: [-118.156582 -118.185237 -118.229715 ... -116.2237   -117.090353
 -115.152865]
Population: [68701 55668 47534 ...   116 73006  8062]
Churn Value: [1 0]
CLTV: [5433 5302 3179 ... 2770 4645 5553]
Churn Category: ['Competitor' 'Dissatisfaction' 'Price' 'Other' 'Attitude' nan]
Churn Reason: ['Competitor offered more data' 'Competitor made better offer'
 'Limited range of services' 'Extra data charges'
 'Competitor had better devices' "Don't know" 'Service dissatisfaction'
 'Lack of affordable download/upload speed' 'Product dissatisfaction'
 'Long distance charges' 'Poor expertise of online support'
 'Attitude of support person' 'Network reliability'
 'Competitor offered higher download speeds' 'Moved' 'Price too high'
 'Attitude of service provider' 'Poor expertise of phone support'
 'Deceased' nan 'Lack of self-service on Website']
Total Customer Svc Requests: [5 1 0 7 2 3 4 6 8 9]
Product/Service Issues Reported: [0 1 2 3 4 5 6]
Customer Satisfaction: [nan  2.  1.  3.  5.  4.]

In [13]:
for i in ["Gender"]:
    df[i].replace({'Male':1,'Female':0},inplace = True)

In [14]:
for col in df:
    print(f'{col}: {df[col].unique()}')

Referred a Friend: [0 1]
Number of Referrals: [ 0  1  6  2  4  3  7  5  8  9 10 11]
Tenure in Months: [ 1  8 18 25 37 27 58 15  7 11  3 13 16 24  4 32 54  2 21 55  5 20 65 49
 43 56 52 33 30 46  9 10 35 44 62 14 12 17 39 68 34 22 19 23 42 41 57 38
 29 66 69 40 31 59 36 45 53 70 47 50 51 72 26  6 28 48 61 71 60 64 67 63]
Offer: ['None' 'Offer E' 'Offer D' 'Offer C' 'Offer B' 'Offer A']
Phone Service: [0 1]
Avg Monthly Long Distance Charges: [ 0.   48.85 11.33 ... 44.99 44.98  8.62]
Multiple Lines: [0 1]
Internet Service: [1 0]
Internet Type: ['Fiber Optic' 'Cable' 'DSL' 'None']
Avg Monthly GB Download: [ 9 19 57 13 15 20 33 26 21 32 31 12 10  8 16  2 11  6 14  0 30 29 24 28
 23 22  7 18 25  4  3  5 27 58 17 53 75 56 52 76 64 45 63 62 78 80 84 65
 90 46 43 94 51 48 73 69 71 42 41 59 47 82 85]
Online Security: [0 1]
Online Backup: [0 1]
Device Protection Plan: [1 0]
Premium Tech Support: [0 1]
Streaming TV: [0 1]
Streaming Movies: [1 0]
Streaming Music: [0 1]
Unlimited Data: [0 1]
Contract: ['Month-to-Month' 'One Year' 'Two Year']
Paperless Billing: [1 0]
Payment Method: ['Bank Withdrawal' 'Credit Card' 'Mailed Check']
Monthly Charge: [41.236 83.876 99.268 ... 72.    65.45  78.7  ]
Total Regular Charges: [  39.65  633.3  1752.55 ... 7362.9   346.45 6844.5 ]
Total Refunds: [ 0.   45.61 13.43 40.95 11.05 29.84 49.57 12.07 40.64 10.2  17.88 37.55
 48.09 32.46 20.23 12.59 43.31  8.13 46.64 23.33 47.2  33.25 33.73 49.06
 25.79 15.24 26.99 44.58 20.16  8.88 12.48  6.79 39.29 44.31  5.49 25.67
  9.49 29.17 19.25 45.69 29.88 39.93 26.98 11.83 16.58 17.16 18.85 37.64
 41.2  12.19 45.81 49.53 21.52 29.   29.99 21.08 36.4  21.17  6.26 17.91
 34.67 28.93 41.23 47.73 40.46 15.41 38.98 16.73 27.15 45.82 39.18 31.05
 20.45  6.65 47.04 15.2   1.69 43.66 24.36 27.89  6.11  7.43 25.07 48.66
 36.52 38.09 24.98 21.71 36.78 30.75 25.55 17.19 33.1  32.71  4.76 44.81
  3.33 19.16 31.58  1.09 18.64 44.17 17.76 33.07  8.74  4.48 36.6  33.43
 45.44 18.55 33.21 48.25 21.72 21.69 14.22 45.37 27.6  10.17 36.44 13.03
 23.89 11.   34.29 48.26 35.82 15.73  9.36 19.67 39.27 41.85 40.   12.81
  4.73 27.38 14.24 13.01 11.45 28.35  7.39 35.05 41.18 30.46 48.61 26.02
 38.48 14.23 40.15 48.95 24.44  9.68 23.72 20.29 48.54  4.96 18.21  1.27
 22.96 28.49 19.5   8.35 35.7  17.01 34.69  4.93 35.34 18.39 27.3  44.16
 34.09 36.61 18.72 44.63 23.97 38.42  1.48  2.93 10.76 20.28 42.18 40.79
 41.21  2.29 24.08 36.29 30.26  4.6  41.67 15.62 46.78 14.49 25.84 16.97
 23.67 46.56 27.09 10.23 15.57 26.55  3.2  21.6  17.14  5.73 32.09  1.83
 47.19 14.21 38.15  8.3  31.39 12.55 11.48 43.38 49.37  9.34 38.61 37.06
 43.25 23.28 45.07 44.9  23.61 19.89 38.84  1.01 14.67 37.37 21.32 36.04
 49.51 47.91 11.72 29.76  1.99 40.62 18.84  9.22 33.8   9.73 46.07 47.87
 39.99 14.76  2.24 42.89 16.12 38.37 47.36 33.76 12.8  23.01 12.16 45.75
 28.42 37.03 38.46 46.66 35.61 18.89  1.66 17.6  21.35 29.32 23.92 29.5
 16.86 42.64  1.31 10.57 34.44 13.07 22.34 43.95 37.44 25.57 14.93 46.75
 28.7   2.28 47.02 16.85 29.11 32.55  5.44 27.79 43.68 41.74  2.18  3.26
 26.87 10.47 37.45 34.16 17.5  11.37 46.81 15.02 19.63 45.47 39.92 22.55
  3.34 17.05 38.33 47.79 24.92 40.54  5.55 30.22  5.47 44.   28.98 49.38
 37.68 18.17 36.38 26.83 29.21 18.88 33.67 17.3  17.03  3.55 25.62 18.62
  9.39  5.9   5.01 42.57 42.43  4.7  21.53 21.58 35.28 28.83 38.57 29.41
 10.65 42.29 16.38 36.66 39.45 29.64 26.32 11.85 16.26 20.17 32.59 16.36
 22.53  6.72 36.22 38.34 28.08 17.96 33.29 24.9  15.38  5.15  6.41 41.66
 46.06 33.13 12.66 48.79  3.59 44.86 34.83 49.79 44.53 47.45 13.37  2.81
 44.13 23.13  2.76 46.99 23.16 44.42 48.59 11.8  17.17 15.76  2.97 15.31
 45.54 14.15 32.53 22.97 21.25 36.02 39.68 23.39 20.87 26.7   3.85  3.51
 35.23  9.48 36.13 44.51  4.08 34.45 16.96 16.91 43.12 49.76 23.5  29.95
  9.99 33.24 28.63 10.7  36.92 27.01 42.34 34.47  9.79 26.37  8.96 21.9
  4.25 16.56 10.28 46.67 14.78 49.23 35.01  9.35 37.04 49.24 32.65 39.15
 18.78 14.57 49.22 16.27  5.83 35.44 29.29 47.59 46.39 24.07  8.5  23.47
 29.59 28.09  6.49 34.59 47.55 37.01 43.76 25.98 12.26 37.49 19.13  1.65
 31.9  21.81 15.17 14.3  22.72  8.53 46.26 15.43 25.49 17.33 45.6  25.24
  2.62 36.07 29.93 23.79 22.4  16.89  7.3  16.99 41.33 30.45 30.14 24.99
 30.53 32.24  4.68  4.18  2.21 19.32 25.92 45.46 25.42 43.96 38.65 49.02
 19.12 20.19 26.84 40.41 19.31 48.23 45.38 27.24]
Total Extra Data Charges: [   0.    120.    327.   ...  229.29   17.84 4344.  ]
Total Long Distance Charges: [   0.    390.8   203.94 ...  865.2  2135.52 2043.36]
Gender: [1 0]
Age: [78 74 71 80 72 76 66 70 77 65 67 68 69 79 75 73 37 19 31 23 38 21 29 61
 27 20 56 51 48 32 34 41 30 26 62 64 45 53 63 42 24 54 39 43 50 22 40 47
 60 52 55 59 49 58 25 28 33 44 57 46 36 35]
Under 30: [0 1]
Senior Citizen: [1 0]
Married: [0 1]
Dependents: [0 1]
Number of Dependents: [0 1 3 2 5 4 6 7 8 9]
City: ['Los Angeles' 'Inglewood' 'Whittier' ... 'Topaz' 'Jacumba' 'Holtville']
Zip Code: [90022 90063 90065 ... 91934 92105 92250]
Latitude: [34.02381  34.044271 34.108833 ... 32.649787 32.741859 32.811001]
Longitude: [-118.156582 -118.185237 -118.229715 ... -116.2237   -117.090353
 -115.152865]
Population: [68701 55668 47534 ...   116 73006  8062]
Churn Value: [1 0]
CLTV: [5433 5302 3179 ... 2770 4645 5553]
Churn Category: ['Competitor' 'Dissatisfaction' 'Price' 'Other' 'Attitude' nan]
Churn Reason: ['Competitor offered more data' 'Competitor made better offer'
 'Limited range of services' 'Extra data charges'
 'Competitor had better devices' "Don't know" 'Service dissatisfaction'
 'Lack of affordable download/upload speed' 'Product dissatisfaction'
 'Long distance charges' 'Poor expertise of online support'
 'Attitude of support person' 'Network reliability'
 'Competitor offered higher download speeds' 'Moved' 'Price too high'
 'Attitude of service provider' 'Poor expertise of phone support'
 'Deceased' nan 'Lack of self-service on Website']
Total Customer Svc Requests: [5 1 0 7 2 3 4 6 8 9]
Product/Service Issues Reported: [0 1 2 3 4 5 6]
Customer Satisfaction: [nan  2.  1.  3.  5.  4.]